# This file was generated by GoReleaser. DO NOT EDIT.
cask "torre-cli" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "b423b58da8837c85be3a2abb7558d60fca098a9c6006596614be4ac1891c66f0"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "efd6bf0e6e83b4172659488e3acbaff6f385f4e475bd4297dcb1c703b7e16a2a"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0c7a30691c36785f48a81346386caaa94dc2d9f9cdb2c077782cee60fd6aff5f"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "13f8764158a032461fec9174a27eeb8dc44c2ffb595e7f884fe93aa1c17f3647"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "torre-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/torre-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "torre"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/torre"]
  end

  # No zap stanza required
end
