# This file was generated by GoReleaser. DO NOT EDIT.
cask "torre-cli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "2dcb467e5a729276543ba1d9ebeea3243100329b2bcc9cedd3d599f033f8eecc"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "14f37e7792f2c767feabf4a10fefd4fb49e99ad78105a70d22cdad0aeb3d3d76"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c08033cbbb22e6e6f79b0e046bd466ba41cac4bded38566ea80749331c59c178"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1151e12ca95170a0d10cf98610c6f1441e9e5124cfd13b8dd4a774b1ab677b71"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "torre-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/torre-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "torre"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/torre"]
  end

  # No zap stanza required

end
