# This file was generated by GoReleaser. DO NOT EDIT.
cask "torre-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "81489145b2f964e6f564c3ff5cae5e25c654adced78037b7f27b8e8195dc7731"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "31eed21b7866443855981a38e3075969aae7fc278cf5ca6305f3c5ef460a1675"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f265ed5e3256c518d1f99f0a9d3662c6b0992d569cb03e194f9b5aaf00c0900"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e93abf7df4ff62405e1cb28674172349a71a6c2e6631d4dc77db025935f1bfef"
      url "https://github.com/jjuanrivvera/torre-cli/releases/download/v#{version}/torre-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "torre-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/torre-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "torre"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/torre"]
  end

  # No zap stanza required

end
